### PR TITLE
fix ms graph migration breaking changes

### PR DESCRIPTION
**Pull request by jaredholloway94**
## Purpose

Fix /deployment/scripts/deploy.ps1 to comply with the [new Microsoft Graph version of the Azure CLI](https://docs.microsoft.com/en-us/cli/azure/microsoft-graph-migration#breaking-changes).

## Does this introduce a breaking change?

```
[x] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by kofiasare266** [comment]
> Hi Jared,

I attempted a new deployment with your pull request but that failed. I am not too sure what is happening. Kindly help.
Screenshot 2022-09-01 171248

**Comment by nkronqvist** [comment]
Also got error when trying the patch. See attached log from install and the error details from Azure failed Deployment. Using a Free Trial of Azure. Any clue what might be the issue? 

[deployment_error.txt](https://github.com/Azure-Samples/azure-digital-twins-unreal-integration/files/9739020/deployment_error.txt)
[deployment_error_azure.txt](https://github.com/Azure-Samples/azure-digital-twins-unreal-integration/files/9739022/deployment_error_azure.txt)

**Comment by kofiasare266** [comment]
> Also got error when trying the patch. See attached log from install and the error details from Azure failed Deployment. Using a Free Trial of Azure. Any clue what might be the issue?
> 
> [deployment_error.txt](https://github.com/Azure-Samples/azure-digital-twins-unreal-integration/files/9739020/deployment_error.txt) [deployment_error_azure.txt](https://github.com/Azure-Samples/azure-digital-twins-unreal-integration/files/9739022/deployment_error_azure.txt)

Hi Nils, the plugin is broken. I am told it is being fixed. So fingers crossed.

**Comment by digitaltriplets** [comment]
> > Also got error when trying the patch. See attached log from install and the error details from Azure failed Deployment. Using a Free Trial of Azure. Any clue what might be the issue?
> > [deployment_error.txt](https://github.com/Azure-Samples/azure-digital-twins-unreal-integration/files/9739020/deployment_error.txt) [deployment_error_azure.txt](https://github.com/Azure-Samples/azure-digital-twins-unreal-integration/files/9739022/deployment_error_azure.txt)
> 
> Hi Nils, the plugin is broken. I am told it is being fixed. So fingers crossed.

Hi everyone,

Is there any update on this issue?

also if someone could respond with examples of what repo-adress, repo-name and branch-name should look like (be replaced with) so i know what i should be looking for. 

many thanks, 
DT

**Comment by vararth** [comment]
I urgently need an update to this.. also facing the same issue

**Comment by adamlash** [comment]
Great changes! Apologies for the lack of movement on this repo, I am in the process of taking care of this repository.

I am running through a quick check to solve some of the issues on this repo, and this solves a few of them. I will reply to the relevant issues located in the larger repo once an end-end deployment has been confirmed.

Merging these changes in.

**Comment by adamlash** [comment]
Hello All on this PR,

I have recently made some more changes in a newer PR fixing up a few bugs and issues related to this repo. Feel free to try this again and see if you get the expected outputs.

Any issues? Feel free to open an issue and I'll get to it ASAP

**Comment by niagara1120** [comment]
image
Oops....I just tried it ! There is still an error

**Pull request merged**
